import React, { useState, useEffect } from 'react';
import { AppTab, Trip, DayItinerary, Expense, User } from './types';
import { PRESET_AVATARS } from './constants';
import ItineraryView from './components/ItineraryView';
import ExpenseView from './components/ExpenseView';
import MapView from './components/MapView';
import HomeView from './components/HomeView';
import { db, getDeviceId, ensureUserExists } from './services/firebase';
import { collection, onSnapshot, addDoc, deleteDoc, doc, updateDoc, setDoc } from 'firebase/firestore';

// Helper to remove undefined values before sending to Firestore
// Firestore does not support 'undefined' as a value
const sanitizeForFirestore = (data: any) => {
  return JSON.parse(JSON.stringify(data));
};

const App: React.FC = () => {
  // Global App State
  const [trips, setTrips] = useState<Trip[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [activeTripId, setActiveTripId] = useState<string | null>(null);
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  
  // Theme State
  const [isDarkMode, setIsDarkMode] = useState(() => {
    try {
        const saved = localStorage.getItem('wanderlist_theme');
        return saved === 'dark';
    } catch { return false; }
  });

  // Tab State for Detail View
  const [activeTab, setActiveTab] = useState<AppTab>(AppTab.ITINERARY);

  // Modals
  const [showProfileModal, setShowProfileModal] = useState(false);
  const [editingUser, setEditingUser] = useState<{name: string, avatar: string}>({ name: '', avatar: '' });

  // Trip Edit Modal
  const [showTripSettings, setShowTripSettings] = useState(false);
  const [editingTrip, setEditingTrip] = useState<{
      destination: string, 
      startDate: string, 
      endDate: string, 
      coverImage: string,
      coverImageDark: string
  }>({ destination: '', startDate: '', endDate: '', coverImage: '', coverImageDark: '' });

  // Initialize Theme
  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.classList.add('dark');
      localStorage.setItem('wanderlist_theme', 'dark');
    } else {
      document.documentElement.classList.remove('dark');
      localStorage.setItem('wanderlist_theme', 'light');
    }
  }, [isDarkMode]);

  const toggleTheme = () => setIsDarkMode(!isDarkMode);

  // Initialize User & Firebase Listeners
  useEffect(() => {
    const init = async () => {
        const deviceId = getDeviceId();
        await ensureUserExists(deviceId);
    };
    init();

    if (db) {
        // Listen to Users
        const unsubUsers = onSnapshot(collection(db, 'users'), (snapshot) => {
            const usersData = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as User));
            setUsers(usersData);
            const myId = getDeviceId();
            const me = usersData.find(u => u.id === myId);
            if (me) setCurrentUser(me);
        });

        // Listen to Trips
        const unsubTrips = onSnapshot(collection(db, 'trips'), (snapshot) => {
             const tripsData = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as Trip));
             // Sort by startDate desc
             tripsData.sort((a, b) => new Date(b.startDate).getTime() - new Date(a.startDate).getTime());
             setTrips(tripsData);
        });

        return () => {
            unsubUsers();
            unsubTrips();
        };
    } else {
        // Fallback for offline mode / no DB
        const myId = getDeviceId();
        const mockUser: User = { id: myId, name: '訪客', avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Felix' };
        setUsers([mockUser]);
        setCurrentUser(mockUser);
    }
  }, []);

  // Handlers
  const handleAddTrip = async (newTrip: Trip) => {
     if (!db) {
         setTrips([newTrip, ...trips]);
         return;
     }
     // Use setDoc to preserve the ID generated by HomeView
     // Sanitize to prevent "Unsupported field value: undefined" errors
     const safeTrip = sanitizeForFirestore(newTrip);
     await setDoc(doc(db, 'trips', newTrip.id), safeTrip);
  };

  const handleDeleteTrip = async (tripId: string) => {
      if (!db) {
          setTrips(trips.filter(t => t.id !== tripId));
          if (activeTripId === tripId) setActiveTripId(null);
          return;
      }
      await deleteDoc(doc(db, 'trips', tripId));
      if (activeTripId === tripId) setActiveTripId(null);
  };

  const handleUpdateUser = async () => {
      // Use existing ID or fallback to device ID
      const myId = currentUser?.id || getDeviceId();
      const newName = editingUser.name || 'User';
      const newAvatar = editingUser.avatar || PRESET_AVATARS[0];
      
      const updatedUser: User = { 
          id: myId, 
          name: newName, 
          avatar: newAvatar 
      };
      
      // Update local state immediately (Optimistic UI)
      setCurrentUser(updatedUser);
      setUsers(prev => {
          const exists = prev.find(u => u.id === myId);
          if (exists) return prev.map(u => u.id === myId ? updatedUser : u);
          return [...prev, updatedUser];
      });
      
      // Close Modal immediately
      setShowProfileModal(false);

      if (db) {
        try {
            await setDoc(doc(db, 'users', myId), {
                name: newName,
                avatar: newAvatar
            }, { merge: true });
        } catch(e) {
            console.error("Update user failed", e);
            alert("更新失敗: 圖片可能過大或網絡問題");
        }
      }
  };

  const handleAvatarUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
         alert("圖片過大，請選擇小於 5MB 的圖片");
         return;
      }

      const reader = new FileReader();
      reader.onload = (event) => {
        // Compress Image logic
        const img = new Image();
        img.onload = () => {
            const canvas = document.createElement('canvas');
            // Max dimensions 300px is enough for avatars
            const MAX_SIZE = 300; 
            let width = img.width;
            let height = img.height;
            
            if (width > height) {
                if (width > MAX_SIZE) {
                    height *= MAX_SIZE / width;
                    width = MAX_SIZE;
                }
            } else {
                if (height > MAX_SIZE) {
                    width *= MAX_SIZE / height;
                    height = MAX_SIZE;
                }
            }
            
            canvas.width = width;
            canvas.height = height;
            const ctx = canvas.getContext('2d');
            if (ctx) {
                ctx.drawImage(img, 0, 0, width, height);
                // Compress to JPEG 0.7 quality to reduce size for Firestore (max 1MB doc limit)
                const compressedBase64 = canvas.toDataURL('image/jpeg', 0.7);
                setEditingUser(prev => ({ ...prev, avatar: compressedBase64 }));
            }
        };
        img.src = event.target?.result as string;
      };
      reader.readAsDataURL(file);
    }
  };

  const activeTrip = trips.find(t => t.id === activeTripId);

  // Wrappers to update specific fields of the active trip
  const setDaysWrapper = (action: React.SetStateAction<DayItinerary[]>) => {
      if (!activeTrip) return;
      
      const newDays = typeof action === 'function' ? action(activeTrip.days) : action;
      
      if (!db) {
          setTrips(trips.map(t => t.id === activeTrip.id ? { ...t, days: newDays } : t));
          return;
      }
      updateDoc(doc(db, 'trips', activeTrip.id), { days: sanitizeForFirestore(newDays) });
  };

  const setExpensesWrapper = (action: React.SetStateAction<Expense[]>) => {
      if (!activeTrip) return;
      
      const newExpenses = typeof action === 'function' ? action(activeTrip.expenses) : action;
      
      if (!db) {
          setTrips(trips.map(t => t.id === activeTrip.id ? { ...t, expenses: newExpenses } : t));
          return;
      }
      updateDoc(doc(db, 'trips', activeTrip.id), { expenses: sanitizeForFirestore(newExpenses) });
  };

  // Logic to handle Trip Update
  const handleOpenTripSettings = () => {
      if (!activeTrip) return;
      setEditingTrip({
          destination: activeTrip.destination,
          startDate: activeTrip.startDate,
          endDate: activeTrip.endDate,
          coverImage: activeTrip.coverImage,
          coverImageDark: activeTrip.coverImageDark || ''
      });
      setShowTripSettings(true);
  };

  const handleSaveTripSettings = async () => {
      if (!activeTrip) return;
      if (!editingTrip.destination || !editingTrip.startDate || !editingTrip.endDate) {
          alert("請完整填寫資訊");
          return;
      }

      const start = new Date(editingTrip.startDate);
      const end = new Date(editingTrip.endDate);
      if (start > end) {
          alert("結束日期不能早於開始日期");
          return;
      }

      // Calculate Day Adjustments
      const oldStart = new Date(activeTrip.startDate);
      const timeDiff = start.getTime() - oldStart.getTime();
      const dayDiff = Math.round(timeDiff / (1000 * 3600 * 24));
      
      const totalDays = Math.ceil((end.getTime() - start.getTime()) / (1000 * 3600 * 24)) + 1;

      // Create new days array
      let newDays = [...activeTrip.days];

      // 1. Shift dates
      if (dayDiff !== 0) {
          newDays = newDays.map(day => {
              const d = new Date(day.date);
              d.setDate(d.getDate() + dayDiff);
              return { ...day, date: d.toISOString().split('T')[0] };
          });
      }

      // 2. Adjust Length
      if (newDays.length > totalDays) {
          // Truncate
          if (window.confirm("新的日期範圍較短，將會刪除多餘的天數行程。確定嗎？")) {
             newDays = newDays.slice(0, totalDays);
          } else {
              return; // Cancel
          }
      } else if (newDays.length < totalDays) {
          // Append
          const daysToAdd = totalDays - newDays.length;
          const lastDate = newDays.length > 0 ? new Date(newDays[newDays.length - 1].date) : new Date(start);
          if (newDays.length === 0) lastDate.setDate(lastDate.getDate() - 1); // Adjust if starting from 0

          for (let i = 0; i < daysToAdd; i++) {
              lastDate.setDate(lastDate.getDate() + 1);
              newDays.push({
                  id: `d-${Date.now()}-${i}`,
                  date: lastDate.toISOString().split('T')[0],
                  dayLabel: `第 ${newDays.length + 1} 天`,
                  items: []
              });
          }
      }

      // Update Local State
      const updatedTrip = {
          ...activeTrip,
          destination: editingTrip.destination,
          startDate: editingTrip.startDate,
          endDate: editingTrip.endDate,
          coverImage: editingTrip.coverImage,
          coverImageDark: editingTrip.coverImageDark,
          days: newDays
      };

      if (!db) {
          setTrips(trips.map(t => t.id === activeTrip.id ? updatedTrip : t));
      } else {
          // Optimistic
          setTrips(trips.map(t => t.id === activeTrip.id ? updatedTrip : t));
          await updateDoc(doc(db, 'trips', activeTrip.id), sanitizeForFirestore(updatedTrip));
      }

      setShowTripSettings(false);
  };

  // View Routing
  if (!activeTripId) {
      return (
          <HomeView 
            trips={trips} 
            onSelectTrip={setActiveTripId} 
            onAddTrip={handleAddTrip} 
            onDeleteTrip={handleDeleteTrip}
            isDarkMode={isDarkMode}
            toggleTheme={toggleTheme}
          />
      );
  }

  if (!activeTrip) return null;

  return (
    <div className="h-screen w-full flex flex-col bg-[#F2F2F7] dark:bg-[#0B0F19] overflow-hidden text-slate-900 dark:text-slate-100 font-sans transition-colors duration-300">
      
      {/* Header - Reduced Height */}
      <div className="bg-white/80 dark:bg-slate-900/80 backdrop-blur-md pt-6 pb-2 px-4 shadow-sm z-30 flex justify-between items-center shrink-0 border-b border-gray-200 dark:border-white/5 transition-colors duration-300">
        <button onClick={() => setActiveTripId(null)} className="w-10 h-10 rounded-full flex items-center justify-center text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-slate-800 transition-colors">
            <i className="fa-solid fa-chevron-left"></i>
        </button>
        
        {/* Clickable Title for Editing */}
        <button onClick={handleOpenTripSettings} className="flex-1 truncate mx-2 flex flex-col items-center justify-center group">
            <h1 className="text-lg font-black text-center dark:text-white flex items-center gap-2 group-hover:text-blue-500 transition-colors">
                {activeTrip.destination}
                <i className="fa-solid fa-pen text-[10px] opacity-0 group-hover:opacity-100 transition-opacity text-blue-500"></i>
            </h1>
            <span className="text-[10px] text-gray-400 font-mono font-bold">{activeTrip.startDate.replace(/-/g, '.')} - {activeTrip.endDate.replace(/-/g, '.')}</span>
        </button>
        
        <div className="flex gap-2">
             <button 
                onClick={toggleTheme}
                className="w-10 h-10 rounded-full bg-gray-100 dark:bg-slate-800 flex items-center justify-center text-gray-400 dark:text-yellow-400 transition-colors"
             >
                <i className={`fa-solid ${isDarkMode ? 'fa-sun' : 'fa-moon'}`}></i>
             </button>
             <button onClick={() => { 
                 setEditingUser({ name: currentUser?.name || '', avatar: currentUser?.avatar || '' });
                 setShowProfileModal(true); 
             }} className="relative">
                <img src={currentUser?.avatar} alt="Me" className="w-9 h-9 rounded-full border-2 border-white dark:border-slate-700 shadow-sm bg-gray-200 object-cover" />
                <div className="absolute bottom-0 right-0 w-2.5 h-2.5 bg-green-500 border-2 border-white dark:border-slate-900 rounded-full"></div>
             </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 overflow-hidden relative">
         {activeTab === AppTab.ITINERARY && <ItineraryView days={activeTrip.days} setDays={setDaysWrapper} />}
         {activeTab === AppTab.EXPENSES && <ExpenseView expenses={activeTrip.expenses} setExpenses={setExpensesWrapper} users={users} />}
         {activeTab === AppTab.MAP && <MapView days={activeTrip.days} isDarkMode={isDarkMode} />}
      </div>

      {/* Bottom Navigation (Floating Pill Style) */}
      <div className="absolute bottom-8 left-0 right-0 z-30 flex justify-center pointer-events-none">
          <div className="bg-white/90 dark:bg-slate-800/90 backdrop-blur-xl border border-white/50 dark:border-white/10 shadow-[0_8px_32px_rgba(0,0,0,0.1)] dark:shadow-[0_8px_32px_rgba(0,0,0,0.5)] rounded-full p-1.5 flex gap-1 pointer-events-auto transition-all duration-300">
             {[
                 { id: AppTab.ITINERARY, icon: 'fa-calendar-days', label: '行程' },
                 { id: AppTab.EXPENSES, icon: 'fa-wallet', label: '記帳' },
                 { id: AppTab.MAP, icon: 'fa-map', label: '地圖' },
             ].map(tab => (
                 <button 
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`px-6 py-3 rounded-full flex items-center gap-2 transition-all duration-300 
                    ${activeTab === tab.id 
                        ? 'bg-[#007AFF] text-white shadow-md shadow-blue-200 dark:bg-[#1e3a8a] dark:text-blue-100 dark:shadow-blue-900/50' 
                        : 'text-gray-400 dark:text-gray-500 hover:bg-gray-100 dark:hover:bg-slate-700 hover:text-gray-600 dark:hover:text-gray-300'
                    }`}
                 >
                     <i className={`fa-solid ${tab.icon} ${activeTab === tab.id ? 'text-sm' : 'text-lg'}`}></i>
                     {activeTab === tab.id && <span className="text-xs font-bold">{tab.label}</span>}
                 </button>
             ))}
          </div>
      </div>

      {/* Profile Modal */}
      {showProfileModal && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/30 dark:bg-black/60 backdrop-blur-sm p-4 animate-fade-in">
             <div className="bg-white dark:bg-slate-900 rounded-[2rem] p-6 shadow-2xl max-w-sm w-full border border-white/50 dark:border-white/10 animate-scale-up">
                 <div className="flex justify-between items-center mb-6">
                    <h3 className="text-xl font-black text-black dark:text-white">設定個人檔案</h3>
                    <button onClick={() => setShowProfileModal(false)} className="w-8 h-8 bg-gray-100 dark:bg-slate-800 rounded-full flex items-center justify-center text-gray-500 hover:bg-gray-200 dark:hover:bg-slate-700 transition-colors"><i className="fa-solid fa-xmark"></i></button>
                 </div>
                 
                 <div className="flex flex-col items-center mb-6">
                     <div className="relative group">
                        <img src={editingUser.avatar || PRESET_AVATARS[0]} className="w-24 h-24 rounded-full bg-gray-100 dark:bg-slate-800 mb-4 shadow-lg object-cover border-4 border-white dark:border-slate-800" alt="Preview" />
                        <label className="absolute bottom-4 right-0 w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center text-white cursor-pointer shadow-md hover:bg-blue-600 transition-colors">
                            <i className="fa-solid fa-camera text-xs"></i>
                            <input type="file" accept="image/*" className="hidden" onChange={handleAvatarUpload} />
                        </label>
                     </div>
                     
                     <div className="flex gap-2 overflow-x-auto max-w-full pb-2 no-scrollbar w-full justify-center">
                         {PRESET_AVATARS.slice(0, 5).map((url, i) => (
                             <button key={i} onClick={() => setEditingUser({...editingUser, avatar: url})} className={`w-10 h-10 rounded-full shrink-0 border-2 transition-all ${editingUser.avatar === url ? 'border-blue-500 scale-110' : 'border-transparent opacity-50 hover:opacity-100'}`}>
                                 <img src={url} className="w-full h-full rounded-full" alt="" />
                             </button>
                         ))}
                     </div>
                 </div>

                 <div className="space-y-4">
                     <div>
                         <label className="block text-xs font-bold text-gray-400 uppercase mb-2">顯示名稱</label>
                         <input type="text" value={editingUser.name} onChange={e => setEditingUser({...editingUser, name: e.target.value})} className="w-full bg-gray-50 dark:bg-slate-800 p-4 rounded-2xl outline-none font-bold text-black dark:text-white border border-transparent focus:border-blue-500 transition-all placeholder-gray-300" placeholder="您的名字" />
                     </div>
                     <button onClick={handleUpdateUser} className="w-full py-4 bg-black dark:bg-blue-600 rounded-2xl text-white font-bold shadow-lg hover:bg-gray-800 dark:hover:bg-blue-500 transition-all">儲存設定</button>
                 </div>
             </div>
        </div>
      )}

      {/* Trip Settings Modal */}
      {showTripSettings && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/30 dark:bg-black/60 backdrop-blur-sm p-4 animate-fade-in">
             <div className="bg-white dark:bg-slate-900 rounded-[2rem] p-6 shadow-2xl max-w-sm w-full border border-white/50 dark:border-white/10 animate-scale-up">
                 <div className="flex justify-between items-center mb-6">
                    <h3 className="text-xl font-black text-black dark:text-white flex items-center gap-2"><i className="fa-solid fa-gear text-blue-500"></i> 行程設定</h3>
                    <button onClick={() => setShowTripSettings(false)} className="w-8 h-8 bg-gray-100 dark:bg-slate-800 rounded-full flex items-center justify-center text-gray-500 hover:bg-gray-200 dark:hover:bg-slate-700 transition-colors"><i className="fa-solid fa-xmark"></i></button>
                 </div>
                 
                 <div className="space-y-4">
                     <div>
                         <label className="block text-xs font-bold text-gray-400 uppercase mb-2">行程名稱</label>
                         <input type="text" value={editingTrip.destination} onChange={e => setEditingTrip({...editingTrip, destination: e.target.value})} className="w-full bg-gray-50 dark:bg-slate-800 p-3 rounded-2xl outline-none font-bold text-black dark:text-white border border-transparent focus:border-blue-500 transition-all placeholder-gray-300" />
                     </div>
                     
                     <div className="grid grid-cols-2 gap-3">
                         <div>
                            <label className="block text-xs font-bold text-gray-400 uppercase mb-2">封面 (淺色/預設)</label>
                            <input type="text" placeholder="URL" value={editingTrip.coverImage} onChange={e => setEditingTrip({...editingTrip, coverImage: e.target.value})} className="w-full bg-gray-50 dark:bg-slate-800 p-3 rounded-2xl outline-none font-bold text-xs font-mono text-black dark:text-white border border-transparent focus:border-blue-500 transition-all placeholder-gray-300" />
                         </div>
                         <div>
                            <label className="block text-xs font-bold text-gray-400 uppercase mb-2">封面 (深色/選填)</label>
                            <input type="text" placeholder="URL" value={editingTrip.coverImageDark} onChange={e => setEditingTrip({...editingTrip, coverImageDark: e.target.value})} className="w-full bg-gray-50 dark:bg-slate-800 p-3 rounded-2xl outline-none font-bold text-xs font-mono text-black dark:text-white border border-transparent focus:border-blue-500 transition-all placeholder-gray-300" />
                         </div>
                     </div>

                     <div className="grid grid-cols-[1fr_auto_1fr] gap-2 items-end">
                        <div className="w-full">
                            <label className="block text-xs font-bold text-gray-400 uppercase mb-2">開始日期</label>
                            <input type="date" value={editingTrip.startDate} onChange={e => setEditingTrip({...editingTrip, startDate: e.target.value})} className="w-full bg-gray-50 dark:bg-slate-800 p-3 rounded-2xl outline-none font-bold text-black dark:text-white border border-transparent focus:border-blue-500 transition-all dark:[color-scheme:dark] text-sm" />
                        </div>
                        <i className="fa-solid fa-arrow-right text-gray-300 dark:text-gray-600 mb-4 text-xs"></i>
                        <div className="w-full">
                            <label className="block text-xs font-bold text-gray-400 uppercase mb-2">結束日期</label>
                            <input type="date" value={editingTrip.endDate} onChange={e => setEditingTrip({...editingTrip, endDate: e.target.value})} className="w-full bg-gray-50 dark:bg-slate-800 p-3 rounded-2xl outline-none font-bold text-black dark:text-white border border-transparent focus:border-blue-500 transition-all dark:[color-scheme:dark] text-sm" />
                        </div>
                     </div>

                     <p className="text-xs text-gray-400 px-1 bg-yellow-50 dark:bg-yellow-900/10 p-2 rounded-lg border border-yellow-100 dark:border-yellow-900/30 flex items-start gap-2">
                        <i className="fa-solid fa-triangle-exclamation text-yellow-500 mt-0.5"></i>
                        <span>修改日期將會自動調整天數與現有行程的日期。若縮短天數，多餘的行程將被刪除。</span>
                     </p>

                     <button onClick={handleSaveTripSettings} className="w-full py-4 bg-black dark:bg-blue-600 rounded-2xl text-white font-bold shadow-lg hover:bg-gray-800 dark:hover:bg-blue-500 transition-all">儲存變更</button>
                 </div>
             </div>
        </div>
      )}

    </div>
  );
};

export default App;